add workflows

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -417,7 +417,6 @@
 
 
 ############
-
 name: Python application
 
 on:
@@ -471,6 +470,11 @@ jobs:
           ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$REMOTE_HOST << EOF
               set -e  # Stop execution on error
               
+              # Clean up Docker space on EC2 instance
+              echo "Cleaning up Docker space..."
+              docker system prune -a -f
+              docker volume prune -f
+              
               # Install Docker if not installed (for Amazon Linux 2023)
               if ! command -v docker &> /dev/null; then
                   echo "Docker not found. Installing Docker..."
@@ -488,17 +492,11 @@ jobs:
               echo "Pulling Docker image: $IMAGE_NAME"
               docker pull $IMAGE_NAME
               
-              # Stop and remove all running containers
-              echo "Stopping and removing all running containers..."
-              docker stop $(docker ps -q) || true
-              docker rm $(docker ps -a -q) || true
+              # Stop and remove any existing container
+              docker stop $DOCKER_IMAGE || true
+              docker rm $DOCKER_IMAGE || true
               
-              # Remove all unused images
-              echo "Removing all unused Docker images..."
-              docker rmi $(docker images -q) || true
-              
-              # Run the new container
-              echo "Running the new container..."
+              # Run new container
               docker run -d --name $DOCKER_IMAGE -p 80:80 $IMAGE_NAME
           EOF
 
