add workflows

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -252,6 +252,88 @@
 #           rm -f private_key.pem
 
 
+# name: Python application
+
+# on:
+#   push:
+#     branches: ["main"]
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - uses: actions/checkout@v4
+
+#       - name: Build Docker image for FastAPI
+#         run: |
+#           IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/movie-ml-test:${{ github.sha }}"
+#           echo "Building Docker image: $IMAGE_NAME"
+#           docker build -t $IMAGE_NAME .
+
+#       - name: Login to Docker hub
+#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+#       - name: Push Docker image
+#         run: |
+#           IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/movie-ml-test:${{ github.sha }}"
+#           echo "Pushing Docker image: $IMAGE_NAME"
+#           docker push $IMAGE_NAME
+
+#       - name: Deploy to EC2
+#         env:
+#           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
+#           REMOTE_HOST: ${{ secrets.HOST_DNS }}
+#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+#           DOCKER_IMAGE: "movie-ml-test"
+#         run: |
+#           # Debugging: print environment variables
+#           echo "DOCKER_USERNAME: $DOCKER_USERNAME"
+#           echo "DOCKER_IMAGE: $DOCKER_IMAGE"
+          
+#           # Install SSH client
+#           sudo apt-get update && sudo apt-get install -y ssh
+
+#           # Save the private key and set permissions
+#           echo "$SSH_PRIVATE_KEY" > private_key.pem
+#           chmod 600 private_key.pem
+
+#           # SSH into EC2 and deploy the Docker container
+#           ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$REMOTE_HOST << 'EOF'
+#               set -e  # Stop execution on error
+              
+#               # Install Docker if not installed (for Amazon Linux 2023)
+#               if ! command -v docker &> /dev/null; then
+#                   echo "Docker not found. Installing Docker..."
+#                   sudo dnf update -y
+#                   sudo dnf install -y docker
+#                   sudo systemctl start docker
+#                   sudo systemctl enable docker
+#                   sudo usermod -a -G docker ec2-user
+#               fi
+              
+#               # Login to Docker Hub
+#               echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+              
+#               # Pull latest Docker image
+#               IMAGE_NAME="${{secrets.DOCKER_USERNAME}}/movie-ml-test:${{ github.sha }}"
+#               echo "Pulling Docker image: $IMAGE_NAME"
+#               docker pull $IMAGE_NAME
+              
+#               # Stop and remove any existing container
+#               docker stop $DOCKER_IMAGE || true
+#               docker rm $DOCKER_IMAGE || true
+              
+#               # Run new container
+#               docker run -d --name $DOCKER_IMAGE -p 80:80 $IMAGE_NAME
+#           EOF
+
+#           # Clean up private key
+#           rm -f private_key.pem
+
+
+
+
 name: Python application
 
 on:
@@ -285,11 +367,14 @@ jobs:
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           REMOTE_HOST: ${{ secrets.HOST_DNS }}
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
           DOCKER_IMAGE: "movie-ml-test"
+          IMAGE_NAME: "${{ secrets.DOCKER_USERNAME }}/movie-ml-test:${{ github.sha }}"
         run: |
           # Debugging: print environment variables
           echo "DOCKER_USERNAME: $DOCKER_USERNAME"
           echo "DOCKER_IMAGE: $DOCKER_IMAGE"
+          echo "IMAGE_NAME: $IMAGE_NAME"
           
           # Install SSH client
           sudo apt-get update && sudo apt-get install -y ssh
@@ -299,7 +384,7 @@ jobs:
           chmod 600 private_key.pem
 
           # SSH into EC2 and deploy the Docker container
-          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$REMOTE_HOST << 'EOF'
+          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$REMOTE_HOST << EOF
               set -e  # Stop execution on error
               
               # Install Docker if not installed (for Amazon Linux 2023)
@@ -313,10 +398,9 @@ jobs:
               fi
               
               # Login to Docker Hub
-              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
               
               # Pull latest Docker image
-              IMAGE_NAME="${{secrets.DOCKER_USERNAME}}/movie-ml-test:${{ github.sha }}"
               echo "Pulling Docker image: $IMAGE_NAME"
               docker pull $IMAGE_NAME
               
@@ -330,4 +414,3 @@ jobs:
 
           # Clean up private key
           rm -f private_key.pem
-
